---
name: add_issues_button
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/47898
rollout_issue_url:
milestone: '13.6'
type: development
group: group::project management
default_enabled: false
