---
name: caching_experiments
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49669
rollout_issue_url: 
milestone: '13.7'
type: development
group: group::adoption
default_enabled: false
