---
name: ci_config_visualization_tab
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48793
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/290117
milestone: '13.7'
type: development
group: group::pipeline authoring
default_enabled: false
