---
name: github_import_pull_request_reviews
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48632
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/289153
milestone: '13.7'
type: development
group: group::import
default_enabled: true
